language: rust
rust: 
  - nightly

cache:
  cargo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-dev
    - clang
    - wget
    - autoconf
    - automake
    - libtool
    - curl
    - make
    - g++
    - unzip
    
install:
    - PROTOC_ZIP=protoc-3.6.1-linux-x86_64.zip
    - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/$PROTOC_ZIP
    - sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
    - rm -f $PROTOC_ZIP

script:
  - cargo test --all
  - cargo build --release

env:
  global:
  - RUST_BACKTRACE=1
  - CC="clang"
